server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:6002/eureka/
spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Seele-ovo/domeservice-config
          username: yueleis
          password: 3654819ow
